# Reusable DevSecOps Pipeline Orchestrator
# Checks -> SAST -> Docker Package -> Trivy Scan -> EC2 Deploy -> DAST Scan
name: DevSecOps

on: 
    push:
        branches: [ master ]
        paths-ignore:
          - 'README.md'
          - '.gitignore'
          - 'LICENSE'

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  sonarqube:
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit

  frontend:
    needs: checks
    uses: ./.github/workflows/frontend-ci.yml
    secrets: inherit

  backend:
    needs: checks
    uses: ./.github/workflows/backend-ci.yml
    secrets: inherit

  trivy-frontend:
    needs: frontend
    uses: ./.github/workflows/trivy-scan.yml
    with:
      image-ref: ${{ vars.DOCKERHUB_USERNAME }}/devboard-frontend:latest
      artifact-name: trivy-frontend-report
    secrets: inherit

  trivy-backend:
    needs: backend
    uses: ./.github/workflows/trivy-scan.yml
    with:
      image-ref: ${{ vars.DOCKERHUB_USERNAME }}/devboard-backend:latest
      artifact-name: trivy-backend-report
    secrets: inherit

  deploy:
    needs: [trivy-frontend, trivy-backend, sonarqube]
    permissions:
      issues: write
      contents: read
    uses: ./.github/workflows/cd.yml
    secrets: inherit

  zap-scan:
    needs: deploy
    permissions:
      issues: write
      contents: read
    uses: ./.github/workflows/zap-scan.yml
    secrets: inherit
