name: SonarQube SAST

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=devboard
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Debug SonarQube Metadata
        run: |
          echo "=== SONAR_HOST_URL ==="
          echo "${SONAR_HOST_URL}" | sed 's/./& /g' # print with spaces to bypass secret masking for debug
          echo "=== report-task.txt ==="
          if [ -f .scannerwork/report-task.txt ]; then
            cat .scannerwork/report-task.txt
          else
            echo "report-task.txt not found!"
          fi
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          